<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from TestGuy_Module_Cli
 * @method void amInPath($dir)
 * @method void execute($command)
 * @method void seeInOutput($text)
 * @method void dontSeeInOutput($text)
 * 
 * Methods from TestGuy_Module_Filesystem
 * @method void openFile($filename)
 * @method void seeInFile($text)
 * @method void dontSeeInFile($text)
 * @method void seeFileFound($filename)
**/


class TestGuy extends BaseTestGuy
{


}

